name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build_linux:
    name: Build and test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['25.3', '26.2', '27.0']
        elixir: ['1.15.7', '1.16.3', '1.17.1']
        exclude:
          - otp: '27.0'
            elixir: '1.15.7'
          - otp: '27.0'
            elixir: '1.16.3'
    env:
      MIX_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install some needed dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential git libtool zlib1g-dev

      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          install-hex: true
          install-rebar: true

      - name: Setup Elixir Project
        run: mix deps.get

      - name: Run Tests
        run: mix test --warnings-as-errors
